---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mission-ratings-api
  name: mission-ratings-api
  namespace: rating-app
spec:
  ports:
  - name: 3000-tcp
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    deployment: mission-ratings-api
---
